-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versión del servidor:         5.5.38 - MySQL Community Server (GPL)
-- SO del servidor:              Win32
-- HeidiSQL Versión:             9.1.0.4867
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
-- Volcando datos para la tabla marcadores.marcadoresimportados: ~554 rows (aproximadamente)
DELETE FROM `marcadoresimportados`;
/*!40000 ALTER TABLE `marcadoresimportados` DISABLE KEYS */;
INSERT INTO `marcadoresimportados` (`idMarcador`, `urlMarcador`, `conceptoMarcador`) VALUES
	(1, 'http://zaragozaciudad.net/azlinux/', 'Zaragoza Linux'),
	(2, 'http://frontendlabs.io/985--paquetes-de-sublime-text-para-acelerar-tu-trabajo', 'front end laboratios'),
	(3, 'http://zaragozaciudad.net/azlinux/', 'Zaragoza Linux'),
	(4, 'http://administracionelectronica.gob.es/ctt/verIniciativaPInfoAdificional.htm?idIniciativa=346#.Ukken9K8Dwo', ' PAe - CTT - Información Adicional - Sistema de Pago Electrónico - Gobierno de Aragón'),
	(5, 'http://1.43.10.30:8080/bce/aceptacion', ' Convocatoria Erasmus + y otros programas de movilidad 2014-2015 (Presentación de impreso de aceptacion hasta 20/12/2015)'),
	(6, 'https://servicios3.aragon.es/sigicon/', ' SIGICON'),
	(7, 'http://1.43.10.30:8080/sigi/', ' 1.43.10.30'),
	(8, 'https://servicios3.aragon.es/sigicon/inf.jsp', ' DEPT. EDUCACIÓN ARAGÓN'),
	(9, 'https://servicios3.aragon.es/sigi/', ' SIGI'),
	(10, 'https://preservicios3.aragon.es/sigicon/', ' SIGICON_PRE_SEGURO'),
	(11, 'https://correoweb.aragon.es/OWA/', ' JAVIER IRANZO BURRIEL - Outlook Web App'),
	(12, 'http://phr-d1.aragon.local:8005/sap/bc/gui/sap/its/zhr_upg_ess?sap-client=300&sap-language=ES', ' Horario SAP'),
	(13, 'https://accesoremoto.aragon.es/LocalDevelopment~essweb~sap.com/,DanaInfo=pxi.aragon.local,Port=50700+login.jsp;jsessionid=(moz-sapcipxi_PXI_07)ID1288953450DB10840803571591939074End;saplb_*=(moz-sapcipxi_PXI_07)75308650', ' Horario - SAP Web Application Server'),
	(14, 'http://97cosas.com/programador/', ' 97 cosas que todo programador debería saber'),
	(15, 'http://struts.apache.org/release/2.2.x/docs/accessing-application-session-request-objects.html', ' Accessing application, session, request objects'),
	(16, 'https://correoweb.aragon.es/OWA/', ' correoweb.aragon.es'),
	(17, 'http://www.um.es/atica/sql---como-usar-subversion-desde-sql-developer-5', ' Area de Tecnologías de la Información y las Comunicaciones Aplicadas de la Universidad de Murcia (ATICA) - SQL - Cómo usar Subversion desde SQL Developer'),
	(18, 'http://www.oracle.com/technetwork/issue-archive/2008/08-jul/o48sql-092467.html', ' SQL Developer: Managing File Versions'),
	(19, 'http://www.educaragon.org/GestionPersonal/personal.asp', ' EducAragón ::: Departamento de Educación, Universidad, Cultura y Deporte. Gobierno de Aragón'),
	(20, 'https://ast.aragon.es/ast/area-personal', ' Área personal | Aragonesa de Servicios Telemáticos (AST) :: Gobierno de Aragón'),
	(21, 'https://servicios3.aragon.es/srt_admin_v3', ' consultar registro telemático srt_admin_v3'),
	(22, 'http://docs.spring.io/spring-data/jdbc/docs/1.1.0.M1/reference/html/orcl.datatypes.html', ' orcl.datatypes.html'),
	(23, 'http://1.12.3.147:8080/sigicon/', ' DEPT. EDUCACIÓN ARAGÓN'),
	(24, 'http://betteratoracle.com/posts/26-passing-arrays-between-java-and-oracle-procedures', ' Passing Arrays between Java and Oracle Procedures - Better At Oracle'),
	(25, 'http://www.springhispano.org/?q=node/2860', ' Acceso a datos con JDBC [Capitulo 13 Documentacion de Referencia v3.1] | SpringHispano.org'),
	(26, 'http://viralpatel.net/blogs/java-passing-array-to-oracle-stored-procedure/', ' Java: Passing Array to Oracle Stored Procedure'),
	(27, 'http://1.12.3.192:5500/em', ' http://1.12.3.192:5500/em'),
	(28, 'http://descubriendooracle.blogspot.com.es/2011/03/crear-un-sencillo-modelo-de-datos-con.html', ' Descubriendo el Mundo Oracle: Crear un sencillo modelo de datos con Oracle SQL Developer Data Modeler'),
	(29, 'https://servicios.aragon.es/sigad-academica', ' Login Sigad Académica'),
	(30, 'http://portalempleado.aragon.es/portal/page?_pageid=193,1&_dad=portal&_schema=PORTAL', ' PORTAL DEL EMPLEADO'),
	(31, 'https://extranet.mecd.es/dana-na/auth/url_default/welcome.cgi', ' Extranet del Ministerio de Educación, Cultura y Deporte'),
	(32, 'http://1.43.10.30:8080/bce/aceptacion', ' Convocatoria Erasmus + y otros programas de movilidad 2014-2015 (Presentación de impreso de aceptacion hasta 20/12/2015)'),
	(33, 'http://localhost:8080/ctpd/start.action?token=f698dc520fb59eea0d2be74055a8116d&idUsuario=jiranzo&idAplicacion=32', ' administrador jiranzo convocatoria primaria 53'),
	(34, 'http://localhost:8080/aplicacionBase', ' aplicación Base start.action'),
	(35, 'http://localhost:8080/ctpd/start.action?token=f698dc520fb59eea0d2be74055a8116d&idUsuario=aetejedor&idAplicacion=32', ' Ana Eva convocatoria primaria'),
	(36, 'http://localhost:8080/ctpd/start.action?token=f698dc520fb59eea0d2be74055a8116d&idUsuario=shernandezc&idAplicacion=32', ' Silvia convocatoria primaria'),
	(37, 'http://localhost:8080/ctpd/start.action?token=f698dc520fb59eea0d2be74055a8116d&idUsuario=lborruel&idAplicacion=32', ' -Lorenzo convocatoria primaria'),
	(38, 'http://localhost:8080/ctpd/start.action?token=f698dc520fb59eea0d2be74055a8116d&idUsuario=bfernandezvelillap&idAplicacion=32', ' Belen convocatoria primaria'),
	(39, 'http://localhost:8080/ctpd/start.action?token=f698dc520fb59eea0d2be74055a8116d&idUsuario=bcapmartin&idAplicacion=32', ' beatriz convocatoria secundaria 54'),
	(40, 'http://localhost:8080/ctpd/start.action?token=f698dc520fb59eea0d2be74055a8116d&idUsuario=iotal&idAplicacion=32', ' ignacio otal convocatoria secundaria 54'),
	(41, 'http://localhost:8080/ctpd/start.action?token=f698dc520fb59eea0d2be74055a8116d&idUsuario=acmateon&idAplicacion=32', ' anacris convocatoria secundaria 54'),
	(42, 'http://localhost:8080/ctpd/start.action?token=f698dc520fb59eea0d2be74055a8116d&idUsuario=mjmorcelle&idAplicacion=32', ' M.J.Morcelle convocatoria secundaria 54'),
	(43, 'http://localhost:8080/ctpd/start.action?token=f698dc520fb59eea0d2be74055a8116d&idUsuario=fcolomae&idAplicacion=32', ' Francisco convocatoria secundaria 54'),
	(44, 'http://desservicios3.aragon.es/geb/', ' Aplicación de Gestión del Departamento de Educación, Universidad, Cultura y Deporte'),
	(45, 'http://localhost:8080/ctpd/start.action?token=f698dc520fb59eea0d2be74055a8116d&idUsuario=eferrer&idAplicacion=32', ' estela varias convocatoria '),
	(46, 'http://localhost:8085/ctpd/start.action?token=f698dc520fb59eea0d2be74055a8116d&idUsuario=jiranzo&idAplicacion=32', ' start.action jiranzo convocatoria primaria 53'),
	(47, 'http://localhost:8080/CTraslados/start.action?token=f698dc520fb59eea0d2be74055a8116d&idUsuario=mescuin&idAplicacion=32', ' start.action mescuin convocatoria secundaria 54'),
	(48, 'http://localhost:8080/manager/html/list', ' /manager'),
	(49, 'http://www.ite.educacion.es/formacion/materiales/85/cd/linux/m2/servidor_dns_bind9.html', ' Servidor DNS bind9 | Redes Linux'),
	(50, 'http://www.redeszone.net/redes/host-en-no-ip-manual-para-crear-un-dynamic-dns-con-no-ip/', ' Host en NO-IP : Manual para crear un Dynamic DNS con NO-IP'),
	(51, 'http://www.subnetmask.info/', ' Network Calculators'),
	(52, 'http://www.dnsstuff.com/tools', ' Toolbox | DNSstuff'),
	(53, 'http://albertomolina.wordpress.com/2009/01/09/nat-con-iptables/', ' NAT con iptables | Desde lo alto del Cerro'),
	(54, 'http://amalaka.wordpress.com/2010/03/04/139/', ' Comandos para Ant | 4M4L4K4k1'),
	(55, 'http://ant.apache.org/manual/', ' Apache Ant™ User Manual'),
	(56, 'http://www.maswifiplus.es/banners/', ' ¡Vaya! Google Chrome no ha podido establecer conexión con la página www.maswifiplus.es.'),
	(57, 'http://www.maswifiplus.info/javier/', ' Index of /javier'),
	(58, 'https://www.hotspotsystem.com/', ' www.hotspotsystem.com'),
	(59, 'http://www.maswifiplus.es/banners/', ' Index of /banners'),
	(60, 'http://www.maswifiplus.info/javier/javi1.php', ' www.maswifiplus.info/javier/javi1.php'),
	(61, 'https://gator3098.hostgator.com:2083/', ' gator3098.hostgator.com'),
	(62, 'http://www.comunidadhosting.com/t/mostrar-imagenes-aleatorias-rotador-de-banner.3658/', ' Mostrar imagenes aleatorias (Rotador de Banner) | ComunidadHosting'),
	(63, 'http://maswifiplus.info/', ' Index of /1'),
	(64, 'http://hotspot.maswifiplus.es/customer/hotspotlogin.php?mode=comb&res=notyet&nasid=multiinformatica_4&test=1&skin=11663&lang=en&theme', ' LOGIN TO HOTSPOT >>>'),
	(65, 'http://blueprintcss.org/', ' Blueprint: A CSS Framework | Spend your time innovating, not replicating'),
	(66, 'http://www.inkilino.com/archivos/css21.pdf', ' chuleta CSS'),
	(67, 'http://cssmenumaker.com/', ' CSS Menu Maker | Drop Down Menu Generator'),
	(68, 'http://www.mclibre.org/consultar/webapps/index.html', ' cursosInteresantes'),
	(69, 'https://www.codeschool.com/', ' www.codeschool.com'),
	(70, 'http://www.codecademy.com/', ' www.codecademy.com'),
	(71, 'http://teamtreehouse.com/', ' teamtreehouse.com'),
	(72, 'http://domtool.yakshavings.co.uk/', ' DOM Tool'),
	(73, 'http://developer.yahoo.com/yui/grids/builder/', ' YUI: CSS Grid Builder'),
	(74, 'http://www.pearltrees.com/#/N-s=1_1278181&N-u=1_49711&N-p=21709343&N-play=0&N-f=1_1278181&N-fa=591856', ' pearltrees • avayaoli • HTML5 • HTML5 tricks'),
	(75, 'http://www.google.com/fonts', ' Google Fonts'),
	(76, 'http://www.java2s.com/Code/Jar/CatalogJar.htm', ' Jar File Download examples (example source code) Organized by topic'),
	(77, 'http://docs.oracle.com/javase/7/docs/', ' Java Platform Standard Edition 7 Documentation'),
	(78, 'http://www.mindviewinc.com/TIJ4/CodeInstructions.html', ' Thinking in Java 4th Edition Source Code'),
	(79, 'http://docs.oracle.com/javase/6/docs/api/overview-summary.html', ' Overview (Java Platform SE 6)'),
	(80, 'http://docs.oracle.com/javaee/6/api/', ' Overview (Java EE 6 )'),
	(81, 'http://www.javatutoriales.com/2013/11/struts-2-parte-7-tags.html', ' Tutoriales de Programacion Java: Struts 2 - Parte 7: Tags'),
	(82, 'http://java-spain.com/bienvenido-java-spaincom', ' Bienvenido a Java-Spain.com | Java-Spain.com'),
	(83, 'http://efytimes.com/e1/fullnews.asp?edid=147231', ' 10 Fastest Ways To Learn Java!'),
	(84, 'https://www.codeschool.com/courses/javascript-road-trip-part-1', ' Learn JavaScript Basics - Code School'),
	(85, 'https://github.com/vhf/free-programming-books/blob/master/free-programming-books-es.md', ' free-programming-books-es.md'),
	(86, 'http://www.javaya.com.ar/index.php?inicio=0', ' JavaYa'),
	(87, 'http://www.etnassoft.com/biblioteca/', ' OpenLibra | EtnasSoft'),
	(88, 'http://www.etnassoft.com/biblioteca/categoria', ' http://www.etnassoft.com/biblioteca/categoria'),
	(89, 'https://github.com/vhf/free-programming-books/blob/master/free-programming-books.md', ' free-programming-books.md'),
	(90, 'https://help.ubuntu.com/lts/serverguide/mysql.html', ' mysql.html'),
	(91, 'http://www.guia-ubuntu.com/index.php/MySQL', ' MySQL'),
	(92, 'http://dev.mysql.com/doc/', ' dev.mysql.com'),
	(93, 'http://www.sqlite.org/cli.html', ' Command Line Shell For SQLite'),
	(94, 'http://www.compileonline.com/execute_sql_online.php', ' Execute SQL Script Online'),
	(95, 'http://sqlitebrowser.org/', ' DB Browser for SQLite'),
	(96, 'http://www.tutorialspoint.com/sqlite', ' http://www.tutorialspoint.com/sqlite'),
	(97, 'http://www.sqlite.org/download.html', ' SQLite Download Page'),
	(98, 'http://www.dataprix.com/oracle_decode_con_like', ' Recopilación scripts y consultas útiles de Oracle | Foro IT de Oracle Database'),
	(99, 'http://127.0.0.1:8080/apex/f?p=4950:1:7959141218398060::NO', ' Home'),
	(100, 'http://antoniovf.wordpress.com/2012/07/15/desinstalar-oracle-database-11g-en-windows/', ' Desinstalar Oracle Database 11g en Windows | Blog de Antonio M. Vélez Ferrón'),
	(101, 'http://docs.oracle.com/database/121/index.htm', ' Oracle Database Online Documentation 12c Release 1 (12.1)'),
	(102, 'http://mioracle.blogspot.com.es/2008/02/tunning-optimizacin.html', ' Oracle SQL y PLSQL.: Tunning (optimización)'),
	(103, 'http://blog.mclaughlinsoftware.com/2011/12/29/oracle-11gr2-on-windows-7/', ' Install Oracle 11gR2 on Windows'),
	(104, 'http://misasignaturasfavoritas.blogspot.com.es/2012/11/crear-una-cuenta-de-usuario-para.html', ' Mis asignaturas favoritas: CREAR UNA CUENTA DE USUARIO PARA INSTALAR ORACLE 11G EN WINDOWS'),
	(105, 'http://docs.oracle.com/cd/B19306_01/server.102/b14200/index.htm', ' Index'),
	(106, 'http://docs.oracle.com/cd/E12151_01/doc.150/e12155/triggers_proc_mysql.htm', ' MySql y oracle Triggers and Stored Procedures'),
	(107, 'http://www.pearltrees.com/#/N-s=1_8430777&N-fa=6478464&N-u=1_868376&N-p=78147934&N-f=1_8430777&N-play=0', ' pearltrees • rlamap • Instalacion y Configuracion'),
	(108, 'http://docs.oracle.com/cd/B19306_01/appdev.102/b14261/toc.htm', ' Contents'),
	(109, 'http://psoug.org/reference/dbms_lob.html', ' Oracle DBMS_LOB BLOB CLOB'),
	(110, 'http://ora.u440.com/dml/select.html', ' ORACLE DML - SELECT'),
	(111, 'http://www.desarrolloweb.com/articulos/2230.php', ' Optimizar consultas SQL'),
	(112, 'http://www.oraclemagazine-digital.com/oraclemagazine/20130910?sub_id=LNP5txupPt71#pg2', ' Oracle Magazine - September/October 2013 - Page C4-Front Cover'),
	(113, 'http://www.oraclemagazine-digital.com/oraclemagazine/20131112?sub_id=LNP5txupPt71#pg2', ' Oracle Magazine - November/December 2013 - Page C4-Front Cover'),
	(114, 'http://mi-blog-sobre-oracle.blogspot.com.es/', ' Mi Blog sobre Oracle'),
	(115, 'http://www.php.net/docs.php', ' PHP: Documentation'),
	(116, 'http://php.net/download-docs.php', ' PHP: Download documentation'),
	(117, 'http://www.lawebdelprogramador.com/codigo/PHP/70-Guardar_y_mostrar_una_imagen_de_una_base_de_datos_MySQL.html', ' PHP - Guardar y mostrar una imagen de una base de datos MySQL'),
	(118, 'http://bakia.co/blogtecnologia/45/obtener-imagenes-de-una-carpeta-dinamicamente-por-php/', ' Obtener imágenes de una carpeta dinamicamente por PHP | Tutoriales de tecnología de bakía.'),
	(119, 'http://www.codecademy.com/es/tracks/php', ' php'),
	(120, 'http://linux.die.net/man/1/rsync', ' rsync(1) - Linux man page'),
	(121, 'https://www.itefix.no/i2/content/cwrsync-free-edition', ' cwRsync - Free Edition | Itefix Consulting & Software'),
	(122, 'http://www.vicente-navarro.com/blog/2008/01/13/backups-con-rsync/', ' Lo hice y lo entendí | Backups con rsync'),
	(123, 'http://rsync.samba.org/examples.html', ' rsync examples'),
	(124, 'http://sleepyhead.de/howto/?href=rsync', ' Simple howtos'),
	(125, 'http://www.springsource.org/download/community', ' Community Downloads | SpringSource.org'),
	(126, 'http://www.springbyexample.org/examples/', ' Spring by Example'),
	(127, 'http://docs.spring.io/spring/docs/3.0.x/spring-framework-reference/pdf/spring-framework-reference.pdf', ' Documentacion Spring'),
	(128, 'http://www.springbyexample.org/', ' Spring by Example'),
	(129, 'http://pajarokillo.wordpress.com/2013/09/17/spring-framework-iii/', ' SpringInyeccionDependencias'),
	(130, 'http://struts.apache.org/release/2.1.x/docs/home.html', ' Apache Struts2 Documentation'),
	(131, 'http://struts.apache.org/release/2.3.x/docs/tag-developers-guide.html', ' Tag Developers Guide'),
	(132, 'http://www.tutorialspoint.com/struts_2/xml_based_validators.htm', ' Struts XML Based Validators'),
	(133, 'http://www.journaldev.com/2230/struts-2-data-tags-example-tutorial', ' Struts 2 Data Tags Example Tutorial | JournalDev'),
	(134, 'https://code.google.com/p/struts2-examples/downloads/list?can=1&q=', ' Downloads - struts2-examples - Code Examples For The Official Struts 2 Documentation - Google Project Hosting'),
	(135, 'http://www.codejava.net/frameworks/struts/sample-struts2-application-for-downloading-files', ' Sample Struts2 application for downloading files'),
	(136, 'http://www.decodigo.com/2009/08/carga-de-archivo-interceptor-fileupload.html', ' Programación con Java: Carga de archivo, Interceptor FileUpload con Struts2'),
	(137, 'http://www.epidataconsulting.com/tikiwiki/tiki-index.php?page=Struts2', ' Base de conocimiento de Epidata : Struts2'),
	(138, 'http://www.mkyong.com/struts2/struts-2-download-file-example/', ' Struts 2 download file example'),
	(139, 'http://www.mkyong.com/tutorials/struts-2-tutorials/', ' Struts 2 Tutorial muy bueno'),
	(140, 'http://mundogeek.net/archivos/2009/02/13/etiquetas-struts-2/', ' Etiquetas Struts 2'),
	(141, 'http://www.decodigo.com/2012/03/integracion-de-struts2-y-spring3-mysql.html?spref=bl', ' Programación con Java: Integración de Struts2 y Spring3, MySQL, Netbeans y Maven'),
	(142, 'http://www.mkyong.com/tutorials/struts-2-tutorials/', ' Struts 2 Tutorial'),
	(143, 'http://mannyjavablog.blogspot.com.es/search?updated-max=2009-07-23T06:51:00-03:00&max-results=7', ' Mânny-Blog'),
	(144, 'http://todosobreprogramacion.blogspot.com.es/2013/02/conociendo-struts-2-proyecto-de-estudio_19.html', ' Desarrollo Avanzado Web: Conociendo Struts 2 - Proyecto de estudio - Validation'),
	(145, 'http://www.javatutoriales.com/2011/06/struts-2-parte-1-configuracion.html', ' Tutoriales de Programacion Java: Struts 2 - Parte 1: Configuración'),
	(146, 'http://todosobreprogramacion.blogspot.com.es/', ' http://todosobreprogramacion.blogspot.com.es'),
	(147, 'https://code.google.com/p/cemicursoj2ee/wiki/Struts2', ' Struts2 - cemicursoj2ee - Guía introductoria a Struts 2 - Curso J2EE: MVCs, Struts 2 y JSF - Google Project Hosting'),
	(148, 'http://www.adictosaltrabajo.com/tutoriales/tutoriales.php?pagina=miPrimeraWebStruts', ' Mi primera Web con Struts'),
	(149, 'http://localhost:8080/Struts2Spring3Ejemplos/', ' Struts2 Spring3_8080'),
	(150, 'http://localhost:8081/Struts2Spring3Ejemplos/', ' Struts2 Spring3_8081'),
	(151, 'http://tortoisesvn.net/docs/release/TortoiseSVN_es/', ' TortoiseSVN'),
	(152, 'http://www.ubuntu.com/', ' Ubuntu'),
	(153, 'http://wiki.ubuntu.com/', ' Ubuntu Wiki (community-edited website)'),
	(154, 'https://answers.launchpad.net/ubuntu/+addquestion', ' Make a Support Request to the Ubuntu Community'),
	(155, 'http://www.debian.org/', ' Debian (Ubuntu is based on Debian)'),
	(156, 'https://one.ubuntu.com/', ' Ubuntu One - The personal cloud that brings your digital life together'),
	(157, 'http://doc.ubuntu-es.org/Comandos_de_uso_frecuente', ' Comandos de uso frecuente - doc.ubuntu-es'),
	(158, 'https://help.ubuntu.com/12.04/', ' help.ubuntu.com'),
	(159, 'http://es.wikieducator.org/Preparaci%C3%B3n_entorno_de_trabajo_en_Ubuntu', ' Preparación_entorno_de_trabajo_en_Ubuntu'),
	(160, 'http://atencion.ula.ve/manuales/unix/resumen.html', ' comandosBasicosUnix'),
	(161, 'http://cb.vu/unixtoolbox.xhtml', ' Unix Toolbox'),
	(162, 'http://tribal.sered.net:2082/', ' Acceso a cPanel'),
	(163, 'https://javieriranzo.neocities.org/', ' neocities The web site of javieriranzo'),
	(164, 'https://neocities.org/', ' Neocities: Create your free website now!'),
	(165, 'http://apostayadrede.neositios.com/', ' Crea tu sitio Web gratis con Neositios'),
	(166, 'http://www.apostayadrede.comocreartuweb.es/', ' Index of /'),
	(167, 'http://gogotraining.com/training/podcasts/index.php', ' IT and Technology Podcasts | GogoTraining'),
	(168, 'http://www.notodocodigo.com/blog/lanzar-la-ejecucion-java-desde-un-archivo-por-lotes/', ' Lanzar la ejecución Java desde un archivo por lotes | No todo código'),
	(169, 'https://wiki.filezilla-project.org/Documentation', ' Documentation - FileZilla Wiki'),
	(170, 'http://rubytutorial.wikidot.com/primer-programa', ' El Primer Programa - Ruby Tutorial'),
	(171, 'https://www.ruby-lang.org/en/', ' Ruby Programming Language'),
	(172, 'http://www.puesenmiordenadorfunciona.blogspot.com.es/', ' El blog de Ana Cortés'),
	(173, 'http://www.java2s.com/', ' Programming tutorials and source code examples'),
	(174, 'http://miscerosyunos.blogspot.com.es/2013/12/jor1k-un-emulador-linux-hecho-en.html', ' jor1k-un-emulador-linux-hecho-en.html'),
	(175, 'http://www.pearltrees.com/#/N-play=0&N-s=1_10446033&N-u=1_1769265&N-p=101729210&N-f=1_10446033&N-fa=10446015', ' pearltrees • hatcollector • Ruby'),
	(176, 'http://overapi.com/', ' OverAPI.com | Collecting all the cheat sheets'),
	(177, 'http://www.tutorialspoint.com/', ' http://www.tutorialspoint.com'),
	(178, 'http://www.cdlibre.org/consultar/catalogo/Utilidades_Archivos-y-carpetas.html', ' Catálogo > Utilidades > Archivos y carpetas - cdlibre.org'),
	(179, 'http://xdebug.org/', ' xdebug.org'),
	(180, 'http://devdocs.io/', ' DevDocs'),
	(181, 'http://blogthinkbig.com/cursos-de-programacion-en-linea/', ' Sitios donde tomar cursos de programación en línea'),
	(182, 'http://ss64.com/', ' SS64 | Command line reference'),
	(183, 'http://builtwith.com/', ' BuiltWith Technology Lookup'),
	(184, 'http://spyrestudios.com/mega-collection-of-cheatsheets-for-designer-developers/', ' Mega Collection Of Cheatsheets for Designers & Developers - SpyreStudios | SpyreStudios'),
	(185, 'http://www.smashingapps.com/2013/10/08/extremely-useful-online-tools-for-web-development.html', ' Extremely Useful Online Tools For Web Development | SmashingApps.com'),
	(186, 'http://ideone.com/', ' http://ideone.com'),
	(187, 'https://codeanywhere.com/editor/#', ' Codeanywhere'),
	(188, 'http://en.wikipedia.org/wiki/Entity%E2%80%93relationship_model', ' Entity–relationship model - Wikipedia, the free encyclopedia'),
	(189, 'http://www.entitymodelling.org/home-1', ' EntityModelling.org'),
	(190, 'http://agu.inter.edu/mrosa/notas%20badm6030/MODELO_DE_ENTIDAD_RELACIONAL.pdf', ' agu.inter.edu/mrosa/notas badm6030/MODELO_DE_ENTIDAD_RELACIONAL.pdf'),
	(191, 'http://www.youtube.com/watch?v=G1Xzp3NYqI8', ' COMO COMPROBAR EL DISPENSADOR DE DETERGENTE DE LAVAVAJILLAS. - YouTube'),
	(192, 'http://days%20of/', ' javier 2.0 05/03/2015 17:36:04  83.5'),
	(193, 'http://www.seriesflv.net/ver/olive-kitteridge-1x04.html', ' Olive Kitteridge 1x04 Online Sub Español Gratis'),
	(194, 'http://www.mejortorrent.com/secciones.php?sec=descargas&ap=contar_varios', ' The Honourable Woman - 1ª Temporada [720p]'),
	(195, 'http://www.mejortorrent.com/', ' http://www.mejortorrent.com/'),
	(196, 'http://www.elitetorrent.net/', ' Descargas torrents - EliteTorrent.net'),
	(197, 'http://seriesdanko.com/serie.php?serie=1874', ' Ver Borgen online o descargar -'),
	(198, 'https://github.com/pelos6', ' gioHub pelos6'),
	(199, 'http://livanvivo.blogspot.com.es/2014/01/charlie-engle-regresa-del-infierno.html', ' Nomada ocasional: Charlie Engle regresa del infierno'),
	(200, 'http://livanvivo.blogspot.com.es/2015/03/el-bucle-de-las-miserias.html', ' Nomada ocasional: El bucle de las miserias'),
	(201, 'http://osandarines.com/andadas/jorgeada-2/', ' Jorgeada |'),
	(202, 'http://www.correrdescalzo.com/index.php?option=com_content&view=article&id=77:bosquimanos&catid=46:blog&Itemid=60', ' BOSQUIMANOS'),
	(203, 'http://es.wikiloc.com/wikiloc/view.do?id=827283', ' Wikiloc - ruta monteperdidoextrem - Espierba, Aragón (España)- GPS track'),
	(204, 'http://piritrail.blogspot.com.es/2014/06/running-madness-la-western-states-por.html', ' PiriTrail : Running Madness: la Western States por dentro'),
	(205, 'http://p-guara.com/wordpress/secciones/carreras-por-montana-2/2a-integral-y-7a-carrera-por-montana-tozal-de-guara-2014/', ' Peña Guara'),
	(206, 'http://aunpasodelacima.blogspot.com.es/2013/07/larutadelosperdidos.html', ' larutadelosperdidos.html'),
	(207, 'http://summitsofmylife.com/es#/proyecto', ' Summits of my life'),
	(208, 'http://www.monteperdido.com/ultratrail-sobrarbe/i-kdd-gr-15-plan-broto/presentacion/', ' Presentación - ULTRA-TRAIL SOBRARBE'),
	(209, 'http://community.sony.es/t5/PC-Accesorios/problemas-con-el-boton-assist/m-p/1384102#U1384102', ' problemas con el boton assist - Sony'),
	(210, 'http://www.sony.es/support/es/product/SVE1512B4E', ' SVE1512B4E'),
	(211, 'http://community.sony.es/t5/pc-accesorios/instalar-ubuntu-en-un-vaio-sve1512b4e/m-p/1783743/highlight/true#M16536', ' instalar ubuntu en un VAIO SVE1512B4E - Sony'),
	(212, 'http://community.sony.es/t5/PC-Accesorios/Instalar-Windows-7-64-Bits-en-Vaio-FIT-14-15-quot/m-p/1304626', ' Instalar Windows 7 64 Bits en Vaio FIT 14/15" - Sony'),
	(213, 'http://www.sony.es/support/es/topics/solutions/127370', ' Consejos y soluciones'),
	(214, 'https://areaprivada.orange.es/', ' areaprivada.orange.es'),
	(215, 'https://www.ono.es/clientes/mis-productos/', ' Mis Productos - ONO'),
	(216, 'https://www.iberdrola.es/clientes/index', ' Web de Clientes Iberdrola'),
	(217, 'https://particulares.gruposantander.es/SUPFPA_ENS/BtoChannelDriver.ssobto?dse_operationName=NavLoginSupernet&dse_parentContextName=&dse_processorState=initial&dse_nextEventName=start', ' https://particulares.gruposantander.es/SUPFPA_ENS/BtoChannelDriver.ssobto?dse_operationName=NavLoginSupernet&dse_parentContextName=&dse_processorState=initial&dse_nextEventName=start'),
	(218, 'https://clientes.libertyseguros.es/group/liberty-seguros/tus-productos', ' Tus Seguros - Liberty Seguros'),
	(219, 'http://www.orange.es/', ' Vente a Orange | Móviles, tarifas 4G, ADSL, TV e Internet'),
	(220, 'https://www1.ibercajadirecto.com/ibercaja/asp/Login.asp#', ' Acceso a la banca online de Ibercaja'),
	(221, 'http://www.capzaragoza.com/es/ficha-inmueble/id/25/id_inmueble/9423', ' Ficha inmueble > Home'),
	(222, 'http://www.zaragoza.es/consultaRecibosWeb/consultaReciboAguaPdf.faces', ' Consulta de la factura de agua y basuras'),
	(223, 'http://www.aragon.es/DepartamentosOrganismosPublicos/Departamentos/ObrasPublicasUrbanismoTransportes/AreasTematicas/ViviendaRehabilitacion/fianzas/ci.Fianzas_Deposito.detalleDepartamento?channelSelected=d298c8548b73a210VgnVCM100000450a15acRCRD', ' Depósito de Fianzas - Fianzas - Vivienda y Rehabilitación - Obras Públicas, Urbanismo, Vivienda y Transportes - Departamentos y Organismos Públicos - Gobierno de Aragón'),
	(224, 'http://www.zaragoza.es/juventud/cipaj/anuncios/insertarAnuncio', ' Su anuncio se ha enviado correctamente'),
	(225, 'http://www.capzaragoza.com/', ' CAP: Centro de Alquiler de Particulares'),
	(226, 'http://www.segundamano.es/zaragoza/nissan-vanette/a49494227/', ' Nissan vanette en Zaragoza - Segundamano.es - 49494227'),
	(227, 'https://servicios3.aragon.es/vehiculos/inicio!compruebaServicioConCertificado.action', ' Vehiculos - Modelos 621 - 623'),
	(228, 'http://www.milanuncios.com/furgonetas-de-segunda-mano/nisan-vanete-cargo-112782134.htm', ' MIL ANUNCIOS.COM - nisan vanete cargo'),
	(229, 'http://bateriasbaratas.blogspot.com.es/2012/08/precio-bateria-carrefour-60-ah.html', ' Baterias Baratas para Coche y Moto: Precio Batería Carrefour 60 Ah.'),
	(230, 'https://www.miriadax.net/web/general-navigation/mi-pagina', ' Miriada X'),
	(231, 'http://the-echoplex.net/flexyboxes/', ' Flexy Boxes — CSS flexbox playground and code generation tool'),
	(232, 'http://vishub.org/excursions/628', ' Módulo 1 de HTML5MOOC - enrique'),
	(233, 'https://drive.google.com/#folders/0B9WNF2xrPaO7ODdSMWMyYnBYN2s', ' ejercicios - Google Drive'),
	(234, 'http://svg-edit.googlecode.com/svn-history/r1771/trunk/editor/svg-editor.html', ' SVG-edit'),
	(235, 'https://3584358b54e24c3e5405767ad4d1c3c210db57d4.googledrive.com/host/0B48KCWfVwCIEdFpFWjFMcEZFcVE/', ' https://3584358b54e24c3e5405767ad4d1c3c210db57d4.googledrive.com/host/0B48KCWfVwCIEdFpFWjFMcEZFcVE/'),
	(236, 'http://commons.wikimedia.org/wiki/Category:SVGs_by_subject', ' Category:SVGs by subject - Wikimedia Commons'),
	(237, 'https://centrovirtual.educacion.es/Symfony14/uploads/img_cursos/GWT_Diptico.pdf', ' https://centrovirtual.educacion.es/Symfony14/uploads/img_cursos/GWT_Diptico.pdf'),
	(238, 'http://cursointroduccionandroid.upvx.es/announcements', ' Android: Introducción a la programación'),
	(239, 'https://centrovirtual.educacion.es/Symfony14/uploads/img_cursos/diniciacion_javascript.pdf', ' https://centrovirtual.educacion.es/Symfony14/uploads/img_cursos/diniciacion_javascript.pdf'),
	(240, 'http://es.wikipedia.org/wiki/Google_Web_Toolkit', ' Google Web Toolkit - Wikipedia, la enciclopedia libre'),
	(241, 'https://www.google.com/calendar/render?hl=es', ' Google Calendar'),
	(242, 'http://www.markitdown.net/', ' Notas'),
	(243, 'http://apostayadrede.blogspot.com.es/', ' Aposta y Adrede'),
	(244, 'https://es-es.facebook.com/', ' ¡Bienvenido a Facebook en Español (España)!'),
	(245, 'https://dub119.mail.live.com/default.aspx?n=58618808&fid=1', ' Outlook - javieriranzo@hotmail.com'),
	(246, 'https://www.google.es/maps/dir/Calle+Trinquete,+04116+Las+Negras,+Almer%C3%ADa/Calle+de+San+Lorenzo,+50001+Zaragoza/@39.2458456,-3.4068054,7z/data=!3m1!4b1!4m13!4m12!1m5!1m1!1s0xd7ae8e8da6a2743:0x4b6ec6364804c68e!2m2!1d-2.0152414!2d36.8767287!1m5!1m1!1s0xd5914f185ab876d:0xd6b7cac67690c7d6!2m2!1d-0.875057!2d41.6523924', ' Google Maps'),
	(247, 'http://www.cabogataalmeria.com/', ' Cabo de Gata Parque Natural en Almeria'),
	(248, 'http://www.molinias.com/contacto/', ' Contacto'),
	(249, 'https://www.alsa.es/portal/site/Alsa/template.PAGE/menuitem.a2b8c42c4264a03c66c766c7421000e5/?javax.portlet.tpst=28b12525bd34c9fec845c845421000e5&javax.portlet.prp_28b12525bd34c9fec845c845421000e5=_spageview%3D%252FShowCart.do%26_kraview%3D1&javax.portlet.begCacheTok=com.vignette.cachetoken&javax.portlet.endCacheTok=com.vignette.cachetoken', ' Resumen de la compra - ALSA'),
	(250, 'http://www.logitravel.com/guias-de-viajes/que-visitar-fuerteventura-18_1.html', ' Qué visitar en Fuerteventura: Las Extraordinarias Maravillas Naturales de Fuerteventura - Logitravel.com'),
	(251, 'https://www.google.es/maps/dir/Hotel+Meli%C3%A1+Gorriones,+P%C3%A1jara/C.o.p.a.z.i.fuerteventura+S.l.,+Calle+Punta+de+los+Molinillos,+13,+35627+Costa+Calma,+Las+Palmas/@28.1470417,-14.2340463,490m/data=!3m1!1e3!4m14!4m13!1m5!1m1!1s0xc479d1ecaeae51d:0x642ccd162bb83ad7!2m2!1d-14.245362!2d28.136877!1m5!1m1!1s0xc47995d8e6e31cd:0x2764c67039ac902a!2m2!1d-14.227088!2d28.162213!3e2', ' Google Maps'),
	(252, 'http://www.boa.aragon.es/cgi-bin/EBOA/BRSCGI?CMD=VEROBJ&MLKOB=555622650404', ' www.boa.aragon.es/cgi-bin/EBOA/BRSCGI?CMD=VEROBJ&MLKOB=555622650404'),
	(253, 'http://www.boa.aragon.es/cgi-bin/EBOA/BRSCGI?CMD=VEROBJ&MLKOB=107787471313', ' www.boa.aragon.es/cgi-bin/EBOA/BRSCGI?CMD=VEROBJ&MLKOB=107787471313'),
	(254, 'http://www.boa.aragon.es/cgi-bin/EBOA/BRSCGI?CMD=VEROBJ&MLKOB=684352601919', ' www.boa.aragon.es/cgi-bin/EBOA/BRSCGI?CMD=VEROBJ&MLKOB=684352601919'),
	(255, 'https://www.youtube.com/watch?v=18F3CZveMwg&feature=youtu.be', ' Installing Linux (Ubuntu 13.04) dual boot with Windows 8 (secure boot and UEFI enabled) - YouTube'),
	(256, 'http://askubuntu.com/questions/221835/installing-ubuntu-on-a-pre-installed-windows-8-64-bit-system-uefi-supported', ' dual boot - Installing Ubuntu on a Pre-Installed Windows 8 (64-bit) System (UEFI Supported) - Ask Ubuntu'),
	(257, 'https://www.youtube.com/watch?v=He2SpA9kG7k', ' Windows 8 - Compartir sistema con Ubuntu - YouTube'),
	(258, 'http://servicios.elpais.com/juegos/nuevos/sudoku/', ' Sudoku Diario > Juegos en EL PAÍS'),
	(259, 'https://mail.google.com/mail/u/0/#inbox', ' Inbox - javieriranzo3@gmail.com - Gmail'),
	(260, 'http://www.youtube.com/watch?v=LVp4WRc6JZ0', ' MOWLIHAWK - EJEMPLO DE SUPERACION (VIDEOCLIP OFICIAL) FT. PATRICIA ROMERO - YouTube'),
	(261, 'http://www.pearltrees.com/', ' pearltrees • javi1234 • marcadorPersonales'),
	(262, 'http://www.youtube.com/watch?v=e7cQ_FG4b58', ' ? Coherence Movie Teaser - YouTube'),
	(263, 'https://www.youtube.com/watch?v=urzzZHGg6go#t=13', ' Dentro de Google - Inside Google - Documental Completo - tutoriales y mas - YouTube'),
	(264, 'http://www.youtube.com/watch?v=Zxb4Oui6m6o', ' Documental-El Eiger-La pared de la muerte - YouTube'),
	(265, 'http://www.jigsawplanet.com/?rc=createpuzzle&ret=%2F', ' Jigsaw Planet - Create Puzzle'),
	(266, 'https://www.youtube.com/watch?v=XwdAj77Ij7k', ' Pavarotti - Nessun Dorma 1994 subtitulos italiano y español - YouTube'),
	(267, 'http://www.4funkies.com/es', ' 4funkies'),
	(268, 'http://www.fromtexttospeech.com/', ' From Text To Speech - Free online TTS service'),
	(269, 'http://jigsaw.w3.org/css-validator/', ' jigsaw.w3.org'),
	(270, 'http://days%20of/', ' 10/12/13 0/0/8 19:18:01'),
	(271, 'http://www.redcoon.es/B477602-Packard-Bell-EasyNote-ENLE11BZ_Port%C3%A1tiles#databox', ' B477602-Packard-Bell-EasyNote-ENLE11BZ_Portátiles'),
	(272, 'http://cursointroduccionandroid.upvx.es/ficha', ' Android: Introducción a la programación'),
	(273, 'http://www.youtube-mp3.org/es', ' Convertidor YouTube a mp3'),
	(274, 'https://www.facebook.com/steve.gibson.3152', ' Steve Gibson'),
	(275, 'http://www.libelium.com/', ' Libelium - Connecting Sensors to the Cloud'),
	(276, 'http://www.arduino.cc/', ' Arduino - HomePage'),
	(277, 'http://localhost:8084/manager/html?org.apache.catalina.filters.CSRF_NONCE=8AF3CCCDF052C3ADABCAE76C6C459C64', ' 403 Access Denied'),
	(278, 'https://www.youtube.com/watch?v=OC0x_s7tj58', ' Riki López - El menú del Bar Rambo - YouTube'),
	(279, 'https://www.dokuwiki.org/dokuwiki', ' dokuwiki [DokuWiki]'),
	(280, 'http://www.aemet.es/es/eltiempo/prediccion/municipios/zaragoza-id50297', ' El Tiempo: Zaragoza (Zaragoza) - Predicción 7 días - Tabla - Agencia Estatal de Meteorología - AEMET. Gobierno de España'),
	(281, 'http://www.booksshouldbefree.com/', ' http://www.booksshouldbefree.com'),
	(282, 'http://atalanta77.blogspot.com.es/2014/04/canciones-para-la-media-de-ciudad.html', ' ATALANTA: Canciones para la Media de Ciudad Rodrigo'),
	(283, 'http://jnotify.sourceforge.net/index.html', ' JNotify'),
	(284, 'http://www.oraclemagazine-digital.com/oraclemagazine/may_june_2014?sub_id=LNP5txupPt71#pg2', ' Oracle Magazine - May/June 2014 - Page C4-Front Cover'),
	(285, 'http://es.answers.yahoo.com/question/index?qid=20081024173705AAdpyQr', ' index'),
	(286, 'https://trello.com/', ' trello.com'),
	(287, 'https://cloudconvert.org/', ' CloudConvert - convert anything to anything'),
	(288, 'http://www.highexistence.com/how-porn-rewires-the-brain-is-porn-bad-for-you/', ' Is watching porn bad for you?'),
	(289, 'https://www.infojobs.net/zaragoza/programador-php-entorno-linux/of-ie6029908174e329e630b205a44b2b2', ' Oferta de empleo: programador-php-entorno-linux en Zaragoza - Bolsa trabajo InfoJobs'),
	(290, 'http://www.daboblog.com/daboblog-el-blog-de-dabo/', ' DaboBlog - Por David Hernández (Dabo), Cibercultura | GNU / Linux | Hacking - Seguridad | SysAdmin |'),
	(291, 'http://cpanel.hostinger.es/index/index', ' Tablero'),
	(292, 'https://www.youtube.com/watch?v=XVJ8kF9NZUA', ' Fan Replacement on Compaq Presario c700 Notebook - YouTube'),
	(293, 'http://www.ingdirect.es/#', ' ING DIRECT, banco online sin comisiones - People in Progress'),
	(294, 'http://seriesdanko.com/capitulo.php?serie=1874&temp=1&cap=03', ' Ver Borgen 1x03 online'),
	(295, 'http://www.rtve.es/alacarta/videos/la-noche-tematica/noche-tematica-sexo-made-in-germany/2974697/', ' La noche temática - Sexo made in Germany, La noche temática - RTVE.es A la Carta'),
	(296, 'http://www.elplacerdelalectura.com/2015/03/gran-cabaret-de-david-grossman.html', ' Gran Cabaret de David Grossman - El Placer de la Lectura'),
	(297, 'http://tel.opendi.es/', ' guía telefónica - Open Directory'),
	(298, 'https://www.amazon.com/gp/buy/thankyou/handlers/display.html?ie=UTF8&asins=149040368X&orderId=111-1104385-6041869&purchaseId=106-6054827-4805032&viewId=ThankYouCart', ' Amazon.com Thanks You'),
	(299, 'http://moodle.teleformacionfp.aragon.es/my/', ' Formación Profesional: Área personal'),
	(300, 'file://home/home/javier/Dropbox/CicloFormativoGradoSuperior/', ' Índice de /home/javier/Dropbox/CicloFormativoGradoSuperior/'),
	(301, 'http://localhost/proyectos/', ' Index of /proyectos'),
	(303, 'http://www.w3cyberlearnings.com/JQuery_Ajax_with_getJSON', ' JQuery Ajax with getJSON - w3cyberlearnings'),
	(304, 'http://datatables.net/forums/discussion/4230/oracle-example', ' Oracle example - DataTables forums'),
	(305, 'http://localhost:8080/proyectos/', ' Index of /proyectos'),
	(306, 'http://jkneb.github.io/ember-crud/#', ' Ember.js CRUD buen ejemplo'),
	(307, 'file:///C:/Users/Javier/Dropbox/CicloFormativoGradoSuperior/practicas_propias/ember_js/AplicacionPruebaEmber.js-master/index.html#/menu/watchColor', ' Primera Aplicacion con Emberjs'),
	(308, 'http://www.adictosaltrabajo.com/tutoriales/tutoriales.php?pagina=PrimeraAplicacionEmber#04', ' Nuestra Primera App con Ember.js'),
	(309, 'http://codehero.co/ember-js-desde-cero-introduccion-e-instalacion/', ' Ember.js desde Cero: Introducción e Instalación - CODEHERO'),
	(310, 'file:///C:/Users/Javier/Dropbox/CicloFormativoGradoSuperior/practicas_propias/ember_js/codeschool/index.html', ' ejemploCodeschoolPropio'),
	(311, 'https://help.ubuntu.com/12.10/serverguide/openldap-server.html', ' OpenLDAP Server'),
	(312, 'http://www.ite.educacion.es/formacion/materiales/85/cd/linux/m6/administracin_de_openldap.html', ' Administración de OpenLDAP | Redes Linux'),
	(313, 'http://www.zytrax.com/books/ldap/ch5/index.html#step1-ldif', ' Chapter 5 OpenLDAP Samples'),
	(314, 'http://www.zytrax.com/books/ldap/', ' Open Source Guide - LDAP for Rocket Scientists - Contents'),
	(315, 'http://albertomolina.files.wordpress.com/2008/07/autenticacion_ldap.pdf', ' albertomolina.files.wordpress.com/2008/07/autenticacion_ldap.pdf'),
	(316, 'http://rogerdudler.github.io/git-guide/index.es.html', ' git - la guía sencilla'),
	(317, 'http://git-scm.com/book/es/Fundamentos-de-Git', ' Git - Fundamentos de Git'),
	(318, 'http://librosweb.es/pro_git/', ' Pro Git, el libro oficial de Git'),
	(319, 'http://www.ite.educacion.es/formacion/materiales/85/cd/linux/m2/servidor_dns_bind9.html', ' Servidor DNS bind9 | Redes Linux'),
	(320, 'http://www.pello.info/filez/firewall/iptables.html', ' IPTABLES manual practico, tutorial de iptables con ejemplos'),
	(321, 'https://security.appspot.com/vsftpd.html', ' vsftpd - Secure, fast FTP server for UNIX-like systems'),
	(322, 'http://yannesposito.com/Scratch/en/blog/Learn-Vim-Progressively/', ' YBlog - Learn Vim Progressively'),
	(323, 'http://www.proftpd.org/docs/', ' The ProFTPD Project: Project Documentation'),
	(324, 'https://sites.google.com/site/sergiocuesta/home', ' Sergio Cuesta Vicente'),
	(325, 'http://my.dot.tk/registration/register?domainname=apostayadrede', ' register'),
	(326, 'http://httpd.apache.org/docs/2.0/es/', ' Documentación del Servidor HTTP Apache 2.0 - Servidor HTTP Apache'),
	(327, 'http://getupcity.wordpress.com/2012/05/03/instalacion-de-un-servidor-web-apache-en-ubuntu-12-04/', ' Instalación de un servidor web Apache en Ubuntu 12.04 | Get Up City!'),
	(328, 'http://informatica.iessanclemente.net/manuais/index.php/Instalaci%C3%B3n_de_Servidor_Web_Apache_en_Debian', ' Instalación de Servidor Web Apache en Debian - Manuais Referencia Departamento Informatica'),
	(329, 'http://recursostic.educacion.es/observatorio/web/es/software/servidores/580-elvira-mifsud', ' apache MEC'),
	(330, 'http://tomcat.apache.org/tomcat-7.0-doc/', ' Tomcat7'),
	(331, 'http://profesores.elo.utfsm.cl/~agv/elo330/2s03/projects/Tomcat/', ' Programación de sistemas - Tomcat'),
	(332, 'http://www.programacion.com/articulo/desplegar_servlets_y_aplicaciones_web_en_tomcat_y_weblogic_server_175', ' Desplegar Servlets y Aplicaciones Web en Tomcat y WebLogic Server. Programación en Castellano.'),
	(333, 'https://glassfish.java.net/documentation.html', ' Glass Fish documentation.html'),
	(334, 'http://www.nabisoft.com/tutorials/glassfish/installing-glassfish-311-on-ubuntu', ' Installing Glassfish 3.1.1 on Ubuntu 10.04 LTS'),
	(335, 'https://help.ubuntu.com/community/OpenSSL', ' OpenSSL - Community Ubuntu Documentation'),
	(336, 'http://www.madboa.com/geek/openssl/', ' OpenSSL Command-Line HOWTO'),
	(337, 'http://www.joseberenguel.com/archivos/imsi/practicas/practica-ssh.pdf', ' www.joseberenguel.com/archivos/imsi/practicas/practica-ssh.pdf'),
	(338, 'http://www3.uji.es/~galdu/ssh_vs_rsh/x165.html', ' Comandos básicos de ssh'),
	(339, 'http://blog.desdelinux.net/ssh-sin-password-solo-3-pasos/', ' Configura conexiones SSH sin password en solo 3 pasos'),
	(340, 'http://betabeers.com/forum/comandos-basicos-controlar-apache-por-ssh-86/', ' Comandos básicos para controlar apache por SSH - Betabeers'),
	(341, 'http://www.linuxtotal.com.mx/index.php?cont=info_seyre_003', ' Entendiendo y usando ssh fingerprint'),
	(342, 'http://www.vicente-navarro.com/blog/2010/06/29/evitando-problemas-con-la-host-key-en-sesiones-no-interactivas-de-openssh/', ' Lo hice y lo entendí | Evitando problemas con la “host key” en sesiones no interactivas de OpenSSH'),
	(343, 'http://wiki.us.es/juanan/wakka.php?wakka=BusquedasVim', ' WikiJuanan : Búsquedas Vim'),
	(344, 'http://bitcoin.org/es/', ' Bitcoin'),
	(345, 'http://www.maestrosdelweb.com/editorial/nmap/', ' Introducción a Nmap | Maestros del Web'),
	(346, 'ftp://ftp.rediris.es/', ' Índice de /'),
	(347, 'http://tldp.org/', ' The Linux Documentation Project'),
	(348, 'ftp://127.0.0.1/', ' ftp localhost'),
	(349, 'http://www.mclarenx.com/2012/08/10/configurar-vsftpd-y-evitar-los-errores-500-y-530/', ' Configurar vsftpd y evitar los errores 500 y 530'),
	(350, 'http://www.linuxparatodos.net/', ' Inicio - linuxparatodos.net'),
	(351, 'http://alistapart.com/', ' alistapart.com'),
	(352, 'http://norfipc.com/inf/ver-encabezados-http.html', ' Mostrar los encabezados HTTP a los visitantes con PHP'),
	(353, 'http://www.linuxparatodos.net/web/comunidad/base-de-conocimiento/-/wiki/Base+de+Conocimiento/Servidor+Web+Apache+en+Ubuntu', ' Servidor Web Apache en Ubuntu - Manuales - linuxparatodos.net'),
	(354, 'http://wiki.metawerx.net/wiki/Web.xml', ' web.xml Reference Guide for Tomcat - Metawerx Java Wiki'),
	(355, 'http://jqueryvalidation.org/', ' http://jqueryvalidation.org'),
	(356, 'http://librojquery.com/', ' Libro gratuito de jQuery en español - Fundamentos de jQuery'),
	(357, 'http://www.javascript-coder.com/form-validation/jquery-form-validation-guide.phtml', ' The Most Indispensable jQuery Form Validation Reference Guide'),
	(358, 'https://www.danpalmer.me/jquery-complexify/', ' https://www.danpalmer.me/jquery-complexify/'),
	(359, 'http://craftpip.github.io/jquery-confirm/', ' jquery-confirm.js | The multipurpose alert & confirm'),
	(360, 'http://jqueryui.com/themeroller/', ' ThemeRoller | jQuery UI'),
	(361, 'http://api.jquery.com/category/effects/', ' Effects | jQuery API Documentation'),
	(362, 'http://jqfundamentals.com/', ' jQuery Fundamentals :: A guide to the basics of jQuery'),
	(363, 'http://jquery.com/', ' jQuery'),
	(364, 'http://api.jquery.com/', ' Documentacion jquery api.jquery.com '),
	(365, 'http://plugins.jquery.com/', ' jQuery Plugin Registry'),
	(366, 'http://plugins.jquery.com/', ' jQuery Plugin Registry'),
	(367, 'http://projects.zoulcreations.com/jquery/jquery-growl/', ' projects.zoulcreations.com/jquery/jquery-growl/'),
	(368, 'http://ksylvest.github.io/jquery-growl/', ' jQuery Growl'),
	(369, 'http://www.elwebmaster.com/articulos/15-plugins-jquery-para-manejar-tablas', ' 15 plugins jQuery para manejar tablas - elWebmaster.com'),
	(370, 'http://cybmeta.com/ajax-con-json-y-php-ejemplo-paso-a-paso/', ' Ajax con jQuery, JSON y PHP: ejemplo paso a paso | CybMeta'),
	(371, 'http://getbootstrap.com/components/', ' Components · Bootstrap'),
	(372, 'http://www.w3schools.com/bootstrap/', ' Bootstrap 3 Tutorial'),
	(373, 'http://librosweb.es/libro/bootstrap_3/', ' Bootstrap 3, el manual oficial'),
	(374, 'http://getbootstrap.com/2.3.2/javascript.html#modals', ' Javascript · Bootstrap'),
	(375, 'http://www.tutorialrepublic.com/twitter-bootstrap-tutorial/bootstrap-modals.php', ' How to Create Modals with Bootstrap 3 - Tutorial Republic'),
	(376, 'http://getbootstrap.com/css/#forms', ' CSS · Bootstrap'),
	(377, 'http://getbootstrap.com/examples/theme/', ' Theme Template for Bootstrap'),
	(378, 'http://www.tutorialspoint.com/bootstrap/bootstrap_modal_plugin.htm', ' Bootstrap Modal Plugin'),
	(379, 'http://bootsnipp.com/forms?version=3%E2%80%8F', ' Bootstrap form builder HTML | Bootsnipp.com'),
	(380, 'http://www.esandra.com/saca-el-maximo-partido-de-sublime-text-v2-con-este-tutorial', ' Saca el Máximo Partido de Sublime Text v.2 con Este Tutorial • eSandra'),
	(381, 'http://frontendlabs.io/985--paquetes-de-sublime-text-para-acelerar-tu-trabajo', ' Paquetes de Sublime Text para acelerar tu trabajo - FrontEnd Labs'),
	(382, 'http://www.formandome.es/linux/instalacion-y-configuracion-de-sublime-text-3-en-ubuntu-14-04-para-desarrollo-web/', ' Instalación y configuración de Sublime Text 3 en Ubuntu 14.04 para desarrollo Web - formandomeformandome'),
	(383, 'http://www.formandome.es/javascript/cors-vs-jsonp-solicitudes-ajax-entre-dominios/', ' CORS y JSONP: Solicitudes AJAX entre dominios. - formandomeformandome'),
	(384, 'http://www.formandome.es/javascript/promises-y-deferreds-en-jquery/', ' Promises y deferreds en jQuery - formandomeformandome'),
	(385, 'http://www.armandojimenez.infenlaces.com/dwec/Tarea1/', ' Tarea 1 de DWEC Armando Jiménez Lucea'),
	(386, 'http://www.javieriranzo.infenlaces.com/2014_2015/DAW_DAWEC/corredores/index.html', ' Practica Jquery Ajax Javier Iranzo'),
	(387, 'http://www.javieriranzo.infenlaces.com/2014_2015/DAW_DAWEC/futbolistas/index.html', ' Practica Jquery Ajax Javier Iranzo'),
	(388, 'http://www.formandome.es/varios/yeoman-automatizar-el-flujo-de-trabajo-en-desarrollo-web/', ' Yeoman: automatizar el flujo de trabajo en desarrollo web - formandomeformandome'),
	(389, 'http://www.formandome.es/javascript/handlebars-precompilacion/', ' Handlebars: precompilación - formandomeformandome'),
	(390, 'http://www.formandome.es/javascript/handlebars-ejemplo-uso/', ' Handlebars: ejemplo de uso - formandomeformandome'),
	(391, 'http://www.formandome.es/javascript/cors-vs-jsonp-solicitudes-ajax-entre-dominios/', ' CORS y JSONP: Solicitudes AJAX entre dominios. - formandomeformandome'),
	(392, 'http://www.formandome.es/linux/instalacion-y-configuracion-de-sublime-text-3-en-ubuntu-14-04-para-desarrollo-web/', ' Instalación y configuración de Sublime Text 3 en Ubuntu 14.04 para desarrollo Web - formandomeformandome'),
	(393, 'http://www.formandome.es/javascript/promises-y-deferreds-en-jquery/', ' Promises y deferreds en jQuery - formandomeformandome'),
	(394, 'http://es.wikieducator.org/Usuario:Juanda/jQuery/Plugins', ' Curso de jQuery-Introducción - WikiEducator'),
	(395, 'https://www.youtube.com/watch?feature=player_embedded&v=GNJh9Twf5Lg', ' Integración del plugin de jQuery datatables con Yeoman. Configuración de Grunt. - YouTube'),
	(396, 'http://elbauldelprogramador.com/mini-tutorial-y-chuleta-de-comandos-git/', ' Git: Mini Tutorial y chuleta de comandos'),
	(397, 'http://rogerdudler.github.io/git-guide/index.es.html', ' git - la guía sencilla'),
	(398, 'https://github.com/juanda99', ' juanda99'),
	(399, 'https://github.com/jdburro', ' jdburro'),
	(400, 'https://datatables.net/development/server-side/php_oracle', ' DataTables - Oracle Development - server-side processing'),
	(401, 'http://editor.datatables.net/examples/index', ' Editor examples - Editor examples index'),
	(402, 'http://www.datatables.net/', ' DataTables | Table plug-in for jQuery'),
	(403, 'http://localhost/cicloFormativoGradoSuperior/DAW_DWEC/tema_4/ejercicioDataTables/datatables_servidor/app/javierEjercicio6.html', ' Ejercicios javier Datatables Servidor'),
	(404, 'http://www.rubenjgarcia.es/2014/06/10/jquery-datatables-ejemplo-de-uso/', ' BUENO jQuery Datatables: Ejemplo de uso | Ruben J Garcia Ruben J Garcia'),
	(405, 'http://www.datatables.net/examples/data_sources/server_side.html#', ' DataTables example - Server-side processing'),
	(406, 'http://chuwiki.chuidiang.org/index.php?title=JQuery_datatables', ' JQuery datatables - ChuWiki'),
	(407, 'http://www.datatables.net/', ' DataTables | Table plug-in for jQuery'),
	(408, 'http://www.cursosenhd.com/tutorial/crear-una-version-para-publicar-del-proyecto/', ' Crear una versión para Publicar del Proyecto 3:39 - Curso de AngularJS Básico-Intermedio Tutorial, Guía, Manual, Videocurso, Videotutorial, Video curso, gratis, online, hd, javascript, framework, Jesús Conde, Mega, Mediafire, YouTube'),
	(409, 'http://frontendlabs.io/1669--gulp-js-en-espanol-tutorial-basico-primeros-pasos-y-ejemplos', ' Gulp.js en español - tutorial básico y primeros pasos'),
	(410, 'http://frontendlabs.io/146--grunt-js-espanol-tutorial-basico-primeros-pasos', ' Grunt.js en español - tutorial básico y primeros pasos'),
	(411, 'http://code.tutsplus.com/tutorials/building-apps-with-the-yeoman-workflow--net-33254', ' Building Apps With the Yeoman Workflow - Tuts+ Code Tutorial'),
	(412, 'http://localhost/CicloFormativoGradoSuperior/proyectos/DAWEC/YEOMAN/practicaValidacionFormularios/practica-validacion-formularios/app/', ' Práctica validación formularios APP'),
	(413, 'http://localhost/CicloFormativoGradoSuperior/proyectos/DAWEC/YEOMAN/practicaValidacionFormularios/practica-validacion-formularios/dist/', ' Práctica validación formularios DIST'),
	(414, 'http://www.armandojimenez.infenlaces.com/dwec/TareaFormulario/dis/formulario.html', ' Mi formulario'),
	(415, 'http://localhost/cicloFormativoGradoSuperior/DAW_DWEC/practicaWebApp/proyectoJavier/practica-ajax-datatables/app/', ' practica ajax datatables'),
	(416, 'http://javieriranzo.infenlaces.com/2014_2015/DAW_DAWEC/practicaWebApp/dist/dist/', ' practica ajax datatables infenlaces DIST'),
	(417, 'http://www.javieriranzo.infenlaces.com/2014_2015/DAW_DAWEC/practicaWebApp/app/app/', ' practica ajax infenlaces APP'),
	(418, 'http://localhost/CicloFormativoGradoSuperior/DAW_DWEC/tema_4/ejercicioDataTables/datatables_servidor/app/ejercicio6javier.html', ' Ejercicios javier Datatables Servidor'),
	(419, 'http://localhost/CicloFormativoGradoSuperior/proyectos/DAWEC/YEOMAN/practicaValidacionFormularios/mostrar-informacion/ejercicio2.html', ' Ejercicio 2 - Datatables obteniendo datos de bbdd en servidor'),
	(420, 'http://localhost/CicloFormativoGradoSuperior/DAW_DWEC/tema_4/ejercicioDataTables/datatables_servidor/app/ejerciciojavier.html', ' Javier practica'),
	(421, 'http://localhost/CicloFormativoGradoSuperior/DAW_DWEC/tema_4/ejercicioDataTables/', ' Index of /CicloFormativoGradoSuperior/DAW_DWEC/tema_4/ejercicioDataTables'),
	(422, 'http://cdnjs.com/libraries/handlebars.js/', ' handlebarsjs - cdnjs.com - the missing cdn for javascript and css'),
	(423, 'http://www.tablesgenerator.com/html_tables', ' HTML Table generator - TablesGenerator.com'),
	(424, 'http://ahoj.io/how-to-delete-web-sql-database-in-google-chrome', ' How to delete Web SQL Database in Google Chrome'),
	(425, 'http://www.markitdown.net/markdown', ' Markdown syntax example preview — MarkItDown'),
	(426, 'http://daringfireball.net/projects/markdown/dingus', ' Daring Fireball: Markdown Web Dingus'),
	(427, 'http://www.sublimetext.info/docs/es/', ' Ayuda de Sublime Text — Ayuda de Sublime Text'),
	(428, 'http://www.formandome.es/course/view.php?id=7', ' Curso: Desarrollo web en entorno cliente'),
	(429, 'file:///C:/Dropbox/CicloFormativoGradoSuperior/DesarrolloWebEntornoCliente/javascript/usandoJavascript.html', ' Ejemplo de código JavaScript'),
	(430, 'http://www.etnassoft.com/biblioteca/ejercicios-de-programacion-en-java/', ' Ejercicios de Programación en Java | EtnasSoft'),
	(431, 'http://docs.emmet.io/', ' Emmet Documentation'),
	(432, 'http://es.wikieducator.org/Usuario:Juanda/javascript/Eventos', ' Eventos'),
	(433, 'http://ironsummitmedia.github.io/startbootstrap-freelancer/#', ' Freelancer - Start Bootstrap Theme'),
	(434, 'https://netbeans.org/kb/docs/webclient/html5-gettingstarted.html', ' Getting Started with HTML5 Applications - NetBeans Tutorial'),
	(435, 'http://localhost:8080/dawec/', ' http://localhost:8080/dawec/'),
	(436, 'http://librosweb.es/javascript/', ' Introducción a JavaScript'),
	(437, 'http://craftpip.com/#works/logo', ' Works | craftpip – Indian Web developer & designer Boniface Pereira'),
	(438, 'file:///home/javier/Dropbox/CicloFormativoGradoSuperior/DAW_DAWEC/tema2/ejercicios1/javascript4.html', ' javascript4.html'),
	(439, 'http://www.mongodbspain.com/es/', ' MongoDB Spain - Comunidad Española sobre MongoDB'),
	(440, 'http://www.dynamicdrive.com/', ' www.dynamicdrive.com'),
	(441, 'http://www.gamarod.com.ar/', ' www.gamarod.com.ar'),
	(442, 'http://www.hotscripts.com/category/scripts/javascript/', ' www.hotscripts.com'),
	(443, 'http://www.particletree.com/features/lightbox-gone-wild/', ' www.particletree.com'),
	(444, 'https://www.youtube.com/watch?v=23L4fZjMpkM', ' Yeoman, jquery validate - YouTube'),
	(445, 'http://blog.spartup.es/es/content/depura-tu-aplicacion-web-javascript-desde-eclipse', ' Depura tu aplicación web JavaScript desde Eclipse | @SpartUp'),
	(446, 'http://yuilibrary.com/yui/quick-start/', ' yuilibrary.com'),
	(447, 'http://www.smarty.net/docsv2/es/', ' Smarty Manual | Smarty'),
	(448, 'http://beta.phpformatter.com/', ' PHP Formatter - PHP Beautifier - PHP Pretty Printer - Home'),
	(449, 'http://fatfreeframework.com/home', ' Home | Fat-Free Framework for PHP'),
	(450, 'http://localhost/cicloFormativoGradoSuperior/DAW_DWES/practicas/practica9_serviciosSOAP/', ' http://localhost/cicloFormativoGradoSuperior/DAW_DWES/practicas/practica9_serviciosSOAP/ no está disponible.'),
	(451, 'http://twig.sensiolabs.org/', ' Homepage - Twig - The flexible, fast, and secure PHP template engine'),
	(452, 'http://localhost/proyectos/DAWES/DAWES2TRIMESTRE/Tema4_TareaLogin/', ' Ejercicio tema 4 Examen php'),
	(453, 'http://localhost/proyectos/DAWES/DAWES2TRIMESTRE/tarea8TiendaSmarty/tarea/login.php', ' Tarea 8: Tienda Web Smarty Plantillas: Login'),
	(454, 'http://localhost/proyectos/DAWES/DAWES2TRIMESTRE/Tarea7_DAWES_sesiones/mostrar.php', ' Tarea 7 sesiones mostrar preferencias'),
	(455, 'http://www.javieriranzo.infenlaces.com/2014_2015/DAW_DAWES/Tema4_TareaLogin/index.php', ' Ejercicio tema 4 Examen php'),
	(456, 'http://es.wikieducator.org/Usuario:ManuelRomero/micursos/DWES/Tema1/Introduccion', ' Usuario:ManuelRomero/micursos/DWES/Tema1/Introduccion - WikiEducator'),
	(457, 'http://es.wikieducator.org/Usuario:ManuelRomero/PHP/servicioWeb', ' Usuario:ManuelRomero/PHP/servicioWeb - WikiEducator'),
	(458, 'http://es.wikieducator.org/Usuario:ManuelRomero/DAW/distancia/BD', ' Usuario:ManuelRomero/DAW/distancia/BD - WikiEducator'),
	(459, 'http://es.wikieducator.org/Usuario:ManuelRomero/DAW/distancia/sesionesBD', ' Usuario:ManuelRomero/DAW/distancia/sesionesBD - WikiEducator'),
	(460, 'http://es.wikieducator.org/Usuario:ManuelRomero/php/opp/introduccion', ' Usuario:ManuelRomero/php/opp/introduccion - WikiEducator'),
	(461, 'http://es.wikieducator.org/Usuario:ManuelRomero/php/introduccion', ' Usuario:ManuelRomero/php/introduccion - WikiEducator'),
	(462, 'http://es.wikieducator.org/Usuario:ManuelRomero/miscursos', ' Usuario:ManuelRomero/miscursos - WikiEducator'),
	(463, 'http://es.wikieducator.org/Usuario:ManuelRomero/php/cookies', ' Usuario:ManuelRomero/php/cookies - WikiEducator'),
	(464, 'http://es.wikieducator.org/Usuario:ManuelRomero/php/sesiones', ' Usuario:ManuelRomero/php/sesiones - WikiEducator'),
	(465, 'http://es.wikieducator.org/ManuelRomero/DAW/distancia/tutorias/Tutoria3/EjSesionesCoockies', ' ManuelRomero/DAW/distancia/tutorias/Tutoria3/EjSesionesCoockies - WikiEducator'),
	(466, 'http://es.wikieducator.org/Usuario:ManuelRomero/php/smarty/introduccion', ' Wiki Manuel Smarty'),
	(467, 'http://es.wikieducator.org/Usuario:ManuelRomero/php/smarty/enunciado', ' Usuario:ManuelRomero/php/smarty/enunciado - WikiEducator'),
	(468, 'https://netbeans.org/kb/docs/php/debugging.html', ' Debugging PHP Source Code in the NetBeans IDE for PHP Editor'),
	(469, 'http://www.php-hispano.net/', ' PHP-Hispano - Comunidad hispana de desarrollo web'),
	(470, 'http://moodle.teleformacionfp.aragon.es/mod/scorm/view.php?id=8772', ' DAW_DWES: DWES04 Guiada.- Desarrollo de aplicaciones web con PHP.'),
	(471, 'http://xpapachox-php.blogspot.com.es/2012/02/creacion-de-un-carrito-de-compras-con.html', ' xPapaChox: Creación de un carrito de compras con PHP, POO y MYSQL...!'),
	(472, 'http://www.manuel.infenlaces.com/tienda/loginW.php', ' Ejemplo Tema 4: Login Tienda Web'),
	(473, 'http://www.md5online.es/cifrar-md5.html', ' MD5 Online | Codificar un MD5'),
	(474, 'http://moodle.teleformacionfp.aragon.es/mod/scorm/view.php?id=8772', ' DAW_DWES: DWES04 Guiada.- Desarrollo de aplicaciones web con PHP.'),
	(475, 'http://www.mclibre.org/consultar/php/', ' Páginas web con PHP. Bartolomé Sintes Marco'),
	(476, 'http://phpfiddle.org/main/code/dmpe-uskp', ' PhpFiddle - PHP/MySQL online IDE and execution server'),
	(477, 'http://manuel.infenlaces.com/baseDatos1/', ' Tarea base de datosFelix'),
	(478, 'http://php.net/manual/es/', ' PHP: Manual de PHP - Manual'),
	(479, 'http://jqueryvalidation.org/files/demo/', ' jQuery validation plug-in - main demo'),
	(480, 'https://s15847154.onlinehome-server.info:8443/', ' Parallels Plesk Panel 10.4.4'),
	(481, 'http://javieriranzo.infenlaces.com/DAW_DIW/practica2/Carousel.htm', ' Carrusel_infenlaces'),
	(482, 'http://www.avanzaenweb.com/', ' AvanzaenWeb | Desarrollo de aplicaciones web, saas y cloud computing'),
	(483, 'http://getbootstrap.com/components/', ' Components · Bootstrap'),
	(484, 'https://www.boottheme.com/app/', ' BootTheme : Web Designer and Theme Generator for Twitter Bootstrap'),
	(485, 'http://www.nomadasdelpirineo.com/', ' www.nomadasdelpirineo.com'),
	(486, 'file:///C:/Users/javier/Dropbox/CicloFormativoGradoSuperior/DAW_DIW/practicas/practica_creacion_webapp/Carousel.htm', ' Carrusel_local'),
	(487, 'http://getbootstrap.com/javascript/#carousel', ' JavaScript · Bootstrap'),
	(488, 'http://librosweb.es/bootstrap_3/', ' Bootstrap 3, el manual oficial'),
	(489, 'http://librosweb.es/css_avanzado/capitulo_1/rollovers_y_sprites.html', ' 1.10. Rollovers y sprites (CSS avanzado)'),
	(490, 'http://www.javieriranzo.infenlaces.com/DAW_DIW/CSS_ZenGarden/index.html', ' CSS Zen Garden: Infenlaces'),
	(491, 'http://www.csszengarden.com/', ' CSS Zen Garden: Original'),
	(492, 'file:///C:/Users/Javier/Documents/Aptana%20Studio%203%20Workspace/CSS_ZenGarden/index.html', ' CSS Zen Garden: Local'),
	(493, 'http://librosweb.es/libro/css_avanzado/capitulo_3/selectores_de_css_3.html', ' 3.6. Selectores de CSS 3 (CSS avanzado)'),
	(494, 'http://webcache.googleusercontent.com/search?q=cache:http://kilianvalkhof.com/2008/css-xhtml/understanding-css-positioning-part-1/', ' Understanding CSS Positioning part 1 • CSS & (X)HTML • Kilian Valkhof'),
	(495, 'http://gallery.theopalgroup.com/selectoracle/', ' ExplicaSelectoresCSS'),
	(496, 'http://www.google.com/fonts', ' Google Fonts'),
	(497, 'http://techtastico.com/post/mockups-online/', ' 15 herramientas en línea para hacer Mockups, Wireframes o Prototipos'),
	(498, 'http://es.wikieducator.org/Usuario:Juanda/html5/Introducci%C3%B3n', ' HTML5 Boilerplate - WikiEducator'),
	(499, 'http://www.javieriranzo.infenlaces.com/', ' Ejercicio 4 Javier'),
	(500, 'http://www.juandadaw.infenlaces.com/', ' Ejercicio 4 Profe'),
	(501, 'http://www.ubuntugeek.com/evoluspencil-the-sketching-and-gui-prototyping-addon-for-firefox.html', ' evoluspencil-the-sketching-and-gui-prototyping-addon-for-firefox.html'),
	(502, 'http://spritegen.website-performance.org/', ' spritegen.website-performance.org'),
	(503, 'http://www.jssor.com/demos/image-slider.html', ' Image Slider Demo - Jssor Slider'),
	(504, 'http://validator.w3.org/', ' The W3C Markup Validation Service'),
	(505, 'http://www.formandome.es/android/cordova-phonegap-instalacion-prueba-android/', ' Cordova: Instalación y prueba sobre plataforma Android - formandomeformandome'),
	(506, 'http://www.html5rocks.com/es/tutorials/video/basics/#toc-formats', ' HTML5 Video - HTML5 Rocks'),
	(507, 'http://librosweb.es/css/', ' Introducción a CSS'),
	(508, 'http://docs.webplatform.org/wiki/Main_Page/es', ' es · Main Page · WPD · WebPlatform.org'),
	(509, 'http://www.w3schools.com/', ' W3Schools Online Web Tutorials'),
	(510, 'http://es.wikieducator.org/Usuario:ManuelRomero/DAW/dwes#Acceso_al_servidor_web_mediante_Nautilus', ' Usuario:ManuelRomero/DAW/dwes - WikiEducator'),
	(511, 'http://matthewjamestaylor.com/blog/equal-height-columns-cross-browser-css-no-hacks', ' equal-height-columns-cross-browser-css-no-hacks'),
	(512, 'http://fu2k.org/alex/css/onetruelayout/example/interactive', ' columnas interactive'),
	(513, 'http://download.brackets.io/', ' Brackets | Downloads'),
	(514, 'http://es.wikieducator.org/Usuario:Juanda/bootstrap/less', ' less'),
	(515, 'file:///C:/Users/javier/Dropbox/CicloFormativoGradoSuperior/DAW_DIW/tema_2_html5/ejercicios/EjerciciosFormularios/formularios1/ejercicio5.html', ' Ejercicio 5'),
	(516, 'http://www.albertoreynolds.es/', ' Marketing Online en Extremadura: Badajoz y Cáceres | SEO y SEM'),
	(517, 'http://es.wikieducator.org/Usuario:ManuelRomero/php/sesiones', ' Usuario:ManuelRomero/php/sesiones - WikiEducator'),
	(518, 'http://www.wordreference.com/es/', ' Diccionarios de Español, Ingles, Francés, Portugués - WordReference.com'),
	(519, 'http://www.teacherjoe.us/NYBJ.html', ' Learn English with Dialogues'),
	(520, 'http://www.learnenglish.de/mistakes/CommonMistakes.html', ' Common Mistakes and Confusing Words in English - Learn English Mistakes'),
	(521, 'http://www.wordreference.com/es/', ' Diccionarios de Español, Ingles, Francés, Portugués - WordReference.com'),
	(522, 'http://www.heraldo.es/index.php/mod.portadas/mem.rss', ' www.heraldo.es/index.php/mod.portadas/mem.rss'),
	(523, 'http://validator.w3.org/feed/', ' W3C Feed Validation Service, for Atom and RSS'),
	(524, 'http://feedvalidator.org/', ' Feed Validator for Atom and RSS'),
	(525, 'http://www.w3schools.com/rss/default.asp', ' RSS Tutorial'),
	(526, 'http://www.mclibre.org/consultar/amaya/index.html', ' Páginas web HTML / XHTML y hojas de estilo CSS. Bartolomé Sintes Marco'),
	(527, 'http://ascii.cl/es/codigos-html.htm', ' Códigos HTML - Tabla de caracteres y símbolos'),
	(528, 'http://planempresa.ipyme.org/Paginas/Home.aspx', ' Plan de Empresa de la DGIPYME'),
	(529, 'http://www.creacionempresas.com/index.php/la-eleccion-de-la-forma-juridica', ' La Elección de la Forma Jurídica'),
	(530, 'http://www.curso-prevencion-riesgo.com/curso/obtener-certificado/', ' Curso Básico Online de Prevención de Riesgos Laborales - Contacto'),
	(531, 'https://moodle2012-13.ua.es/moodle/course/view.php?id=542', ' Curso: 2012-13_TECNOLOGÍAS WEB_9210_9306_9395'),
	(532, 'https://cdnjs.com/', ' cdnjs.com - the missing cdn for javascript and css'),
	(533, 'http://www.illasaron.com/html/content/cinco-excelentes-motores-de-b%C3%BAsqueda-de-c%C3%B3digo-de-programaci%C3%B3n', ' Cinco excelentes motores de búsqueda de código de programación | Videotutoriales Illasaron 2.2'),
	(534, 'https://mega.co.nz/#fm/YswRTIAI', ' MEGA'),
	(535, 'http://www.sqlfiddle.com/', ' http://www.sqlfiddle.com'),
	(536, 'http://it-ebooks.info/book/345/', ' Head First jQuery - Free Download eBook - pdf'),
	(537, 'http://www.sitiolibre.com/curso/gallery.xml', ' Ficheros DAW de José Luis Comesaña'),
	(538, 'http://adellefrank.com/blog/review-how-to-use-install-bluefish-text-editor-windows-vista-windows-7', ' How to use & install the Bluefish Text Editor on Windows Vista or Windows 7 (Review) | Adelle Frank'),
	(539, 'http://www.boa.aragon.es/cgi-bin/EBOA/BRSCGI?CMD=VEROBJ&MLKOB=612152800202', ' www.boa.aragon.es/cgi-bin/EBOA/BRSCGI?CMD=VEROBJ&MLKOB=612152800202'),
	(540, 'http://www.cpilosenlaces.com/cpilosenlaces/secretaria_1_files/solicitud%20convalidacion%20a%20direccion.pdf', ' www.cpilosenlaces.com/cpilosenlaces/secretaria_1_files/solicitud convalidacion a direccion.pdf'),
	(541, 'http://www.leticiacatalan.infenlaces.com/', ' Leticia Catalan'),
	(542, 'http://puntope.es/', ' Miguel Pérez Pellicer | Desarrollador web en Zaragoza'),
	(543, 'http://www.miguelperez.infenlaces.com/', ' Bueno!! Miguel Pérez Pellicer | infenlaces'),
	(544, 'http://www.infenlaces.com/', ' Listado Alumnos 2014-2015'),
	(545, 'https://www.infenlaces.com:8083/login/', ' panel vesta para www.infenlaces.com'),
	(546, 'https://s15847154.onlinehome-server.info:8443/', ' panel de control del subdominio javieriranzo.infenlaces.com'),
	(547, 'http://manuochoaf.infenlaces.com/', ' Ejercicios DISEÑO WEB ENTORNO CLIENTE'),
	(548, 'file:///C:/Users/javier/Dropbox/CicloFormativoGradoSuperior/infenlaces/index.html', ' index.html'),
	(549, 'http://www.manuochoaf.infenlaces.com/', ' Ejercicios DISEÑO WEB ENTORNO CLIENTE'),
	(550, 'file:///home/javier/Dropbox/CicloFormativoGradoSuperior/infenlaces/index.html', ' InfEnlaceLocal'),
	(551, 'http://www.dtaosca.infenlaces.com/', ' PaginaDavid'),
	(552, 'http://www.javieriranzo.infenlaces.com/', ' javier en Servidor InfEnlaces'),
	(553, 'http://www.daw.infenlaces.com/', ' Listado Alumnos'),
	(554, 'https://plus.google.com/u/0/communities/100147853723343869159', ' DAW - Comunidad - Google+'),
	(555, 'https://plus.google.com/u/0/communities/114233891166851914662', ' 1º DAW distancia CPIFP Los Enlaces (13/14) - Comunidad - Google+'),
	(556, 'https://plus.google.com/u/0/communities/101455931561234821124', ' 2º DAW distancia CPIFP Los Enlaces (14/15) - Comunidad - Google+'),
	(557, 'http://www.apache.daw/', ' www.apache.daw'),
	(558, 'http://www.sapache.daw/', ' www.sapache.daw'),
	(559, 'http://abarcarodriguez.com/365/', ' 365 días con @Kinduff javichu'),
	(560, 'file:///C:/Dropbox/CicloFormativoGradoSuperior/DAW.html', 'DAW  '),
	(561, 'http://beabernal.com/', ' Bea Bernal'),
	(562, 'http://theasker.dnsdynamic.com:82/dokuwiki/doku.php?id=cursos:daw:tareas:despliegue_aplicaciones_web:tarea_daw51_dns_ldap_git', ' cursos:daw:tareas:despliegue_aplicaciones_web:tarea_daw51_dns_ldap_git - Desarrollo de Aplicaciones Web'),
	(563, 'http://moodle.cpilosenlaces.com/course/view.php?id=266', ' Curso: Desarrollo web en entorno servidor'),
	(564, 'http://es.wikieducator.org/ManuelRomero/DAW/dwes/Rest', ' ManuelRomero/DAW/dwes/Rest - WikiEducator'),
	(565, 'http://moodle.cpilosenlaces.com/course/view.php?id=219', ' Curso: Lenguajes de marcas y sistemas de gestión de información (DAW)'),
	(566, 'http://librosweb.es/bootstrap_3/', ' librosweb.es'),
	(567, 'http://es.wikieducator.org/Usuario:Juanda', ' Usuario-Juanda'),
	(568, 'http://daw.xtrweb.com/dawiki/doku.php', ' start - Desarrollo de Aplicaciones Web'),
	(569, 'http://maslinux.tk/doku.php', ' start [MasLinux]'),
	(570, 'file:///home/javier/Dropbox/CicloFormativoGradoSuperior/DAW_DIW/practicas/practicaBootstrap/rafting/html/ejercicio.html#', ' rafting'),
	(571, 'http://es.wikieducator.org/Usuario:ManuelRomero', ' Usuario:ManuelRomero - WikiEducator'),
	(572, 'http://www.media.formandome.es/phonegap/presentacion/phonegap_intro.html#/', ' phonegap_intro.html'),
	(573, 'http://www.formandome.es/android/cordova-phonegap-instalacion-prueba-android/', ' www.formandome.es'),
	(574, 'https://bitnami.com/cloud/?utm_source=bitnami&utm_medium=installer&utm_campaign=Bitnami%2BInstallers', ' Bitnami Cloud Hosting a investigar'),
	(575, 'wwwwC:/DATOS/javier/CFGS/CFGS_DIW/w3cSchool/uno.html', ' uno.html local  '),
	(576, 'http://www.fromtexttospeech.com/', ' From Text To Speech - Free online TTS service'),
	(577, 'http://ironsummitmedia.github.io/startbootstrap-freelancer/', ' Freelancer - Start Bootstrap Theme'),
	(578, 'http://www.elladodelmal.com/', ' Un informático en el lado del mal'),
	(579, 'http://ser13gio.blogspot.com.es/2015/04/exo-vol-xx.html', ' ser13gio.blogspot.com.es/2015/04/exo-vol-xx.html'),
	(580, 'http://www.unalineamas.com/analizador-textual/', ' Analizador textual | Una linea mas'),
	(581, 'http://frontendlabs.io/', ' FrontEnd Labs -'),
	(582, 'http://frontendlabs.io/985--paquetes-de-sublime-text-para-acelerar-tu-trabajo', ' Paquetes de Sublime Text para acelerar tu trabajo - FrontEnd Labs'),
	(583, 'file:///C:/Users/Javier/Dropbox/CicloFormativoGradoSuperior/DAW_DIW/tema_7_JQueryMobile/ejerciciosPropios/w3cSchool/uno.html', ' uno.html'),
	(584, 'http://zaragozaciudad.net/azlinux/', ' AZLinux'),
	(585, 'http://regexr.com/', ' regexr.com'),
	(586, 'http://www.oraclemagazine-digital.com/oraclemagazine/january_february_2015?sub_id=LNP5txupPt71#pg2', ' Oracle Magazine - January/February 2015 - Page C4-Front Cover'),
	(587, 'http://www.developerfusion.com/article/84331/jsp-and-custom-tags/', ' JSP and custom tags - Java tutorial - developer Fusion'),
	(588, 'http://codyhouse.co/demo/3d-rotating-navigation/#0', ' 3D Rotating Navigation | CodyHouse'),
	(589, 'http://www.online-convert.com/es', ' Conversor online - convertir gratis vídeos, imágenes, audio y textos'),
	(590, 'http://sgwoodbird.bandcamp.com/', ' SG Woodbird'),
	(591, 'http://mrodriguez.pro/', ' Marc Rodríguez Espinach :: Analista programador FreelanceInicio - Marc Rodríguez Espinach :: Analista programador Freelance'),
	(592, 'http://botica-informatica.blogspot.com.es/', ' Botica informática'),
	(593, 'http://www.ovh.es/', ' Web hosting, cloud y servidores dedicados - OVH'),
	(594, 'http://localhost:8085/aplicacionBase', ' aplicación Base start.action'),
	(595, 'http://www.bilib.es/noticias/noticia/articulo/las-34-mejores-herramientas-online-para-emprended/', ' Las 34 mejores herramientas online para emprendedores: bilib - Centro de Apoyo Tecnológico a Emprendedores'),
	(596, 'http://www.httrack.com/', ' HTTrack Website Copier - Free Software Offline Browser (GNU GPL)'),
	(597, 'http://threejs.org/', ' http://threejs.org'),
	(598, 'http://localhost:8084/manager/html', ' 403 Access Denied'),
	(599, 'http://examplelab.com.ar/inventing-on-principle-en-espanol/', ' Inventing on Principle en español'),
	(600, 'https://trello.com/b/q3FYVloI/nuevo', ' nuevo | Trello'),
	(601, 'http://envios.grupovaughan.com/classroom/newsletter/test_nivel/Common_Errors_By_Spanish_Speakers.pdf', ' envios.grupovaughan.com/classroom/newsletter/test_nivel/Common_Errors_By_Spanish_Speakers.pdf'),
	(602, 'http://aposta.zyro.com/', ' Home'),
	(603, 'http://albertomolina.files.wordpress.com/2008/07/autenticacion_ldap.pdf', ' albertomolina.files.wordpress.com/2008/07/autenticacion_ldap.pdf'),
	(606, 'wewewewewew', ''),
	(607, 'qwqwqqwqqwwww', 'concepto');
/*!40000 ALTER TABLE `marcadoresimportados` ENABLE KEYS */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
